### PR TITLE
Move Haiti Data to Kartoza's standard project structure

### PR DESCRIPTION
**Pull request by euclidian**
I would like to ask about gdal. When I build the project I got error when installing gdal dependencies. Is it because I miss something on django gis related dependencies? So far other container is up and running. I stuck on this error

```
Downloading GDAL-2.2.1.tar.gz (475kB)
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/GDAL.egg-info
    writing pip-egg-info/GDAL.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/GDAL.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/GDAL.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/GDAL.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-MjtzMP/gdal/setup.py", line 339, in <module>
        **extra )
      File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 279, in run
        self.find_sources()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 294, in find_sources
        mm.run()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 525, in run
        self.add_defaults()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 561, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/local/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/local/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-MjtzMP/gdal/setup.py", line 214, in finalize_options
        self.gdaldir = self.get_gdal_config('prefix')
      File "/tmp/pip-build-MjtzMP/gdal/setup.py", line 188, in get_gdal_config
        return fetch_config(option)
      File "/tmp/pip-build-MjtzMP/gdal/setup.py", line 141, in fetch_config
        raise gdal_config_error, e""")
      File "<string>", line 4, in <module>
    __main__.gdal_config_error: [Errno 2] No such file or directory
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-MjtzMP/gdal/
ERROR: Service 'uwsgi' failed to build: The command '/bin/sh -c pip install -r /REQUIREMENTS.txt' returned a non-zero code: 1
make: *** [build] Error 1
```
@cchristelis

### CODE REVIEW

**Comment by euclidian** [comment]
Dockerize is done with some comments:

- I need to remove (temporaryly) all apps that require geonode
- I need to create reverse url to trick templates that use geonode or osgeo url

Next steps is
[ ] Install geonode ( as separate docker? or as app on django project? or any other ideas? )
[ ] put back all apps that should be there
[ ] Remove all dummy data

image

**Comment by meomancer** [comment]
The problem we faced are:
- geonode needs django>=1.8.7, <1.9
- but django oauth needs django>=1.10
- meanwhile some geonode library deprecated, that developed in django1.7

this PR fixes depedencies, but now faced url pattern issue
https://github.com/euclidian/haitidata/pull/1

**Comment by euclidian** [comment]
update :
- migration and translation done

new error: reverse url on document_browse

image

**Comment by euclidian** [comment]
update:

- reverse url fixed

image

new error: 

- OGC Server

**Comment by euclidian** [comment]
@dimasciput changing maps to leaflet gives error like this, and the layer won't show

```
<html>
<head>
<title>GWC Error</title>
<link rel="stylesheet" href="../rest/web/gwc.css" type="text/css"/>
</head>
<body>
<div id="pageHeader"><a id="logo" href="../"><img src="../rest/web/geowebcache_logo.png"/></a></div>
<h4>400: image/png8 is not a supported format for geonode:buildings</h4></body></html>
```

before changing to leaflet:
image

**Comment by cchristelis** [comment]
@euclidian and @dimasciput, I don't think we should be swapping leaflet in here.

**Comment by dimasciput** [comment]
@cchristelis this is working now, we can't use the last map because it's not ol3 or leaflet map. It was react map, and there's no library to draw the polygon or any documentation to do that.

**Comment by dimasciput** [comment]
@cchristelis the other solution is we keep the old map, and when user click download clip button it will open a popup that displays leaflet map. And then they can draw polygons there, what do you think?

**Pull request merged**
