### PR TITLE
Update goeserver version to 2.12.x

### PR DESCRIPTION
**Pull request by dimasciput**
Tested and it's working.

### CODE REVIEW

**Comment by sbsimo** [comment]
hi @dimasciput ,
is this GeoServer upgrade related to a specific issue?

I guess changing the GeoServer version would require also upgrading the GeoServer data dir (http://build.geonode.org/geoserver/latest/data-2.12.x.zip). Is it?

Is the test you mentioned related to the docker build?

**Comment by dimasciput** [comment]
@sbsimo I believe this version will fix memory issue that we have for our current geoserver. 

>  guess changing the GeoServer version would require also upgrading the GeoServer data dir (http://build.geonode.org/geoserver/latest/data-2.12.x.zip). Is it?

Yes you are correct, that's why I need help to migrate the data from the old geoserver to the new geoserver.

**Comment by dimasciput** [comment]
@sbsimo here's my plan, I will build another haiti with geoserver 2.12.x in the haitidata server but with different port. Then we can start migrating the data, after that we can set the new build to default port. What do you think?

**Comment by sbsimo** [comment]
@dimasciput the plan you proposed is fine to me.
I remember a few steps are needed to upgrade the GeoServer data dir with all data in it, I'm going to try finding info in the GeoNode mailing list

**Comment by sbsimo** [comment]
@dimasciput I asked the GeoNode community and it seems that migrating the data directory is not needed for upgrading the GeoServer version. See below the instructions I received:

> if you want just to update GeoServer, there's no need to use backup and restore. Just replace the WAR, it will update the data dir automatically (do a copy first anyway).
> 
> The only thing that you will need to update manually is the geofence-server.properties file as specified here
> 
> http://geonode.readthedocs.io/en/master/tutorials/admin/geoserver_geonode_security/index.html#geoserver-2-12-x-and-above

**Pull request merged**
