### PR TITLE
Add mosaic clipping pages

### PR DESCRIPTION
**Pull request by ppasq**
This PR adds Kartoza's mosaic clipping pages to test site.

### CODE REVIEW

**Comment by ppasq** [comment]
@cchristelis can you please review this PR? Thanks!

**Comment by ppasq** [comment]
@cchristelis @dimasciput @meomancer I get an Internal Server Error when I try to clip the mosaic.
This PR is already on the test site (i.e. http://haitidata.dev.ithacaweb.org/clip/Haiti25cm-PaP-extract). Could you please take a look?

**Comment by cchristelis** [comment]
Hi @ppasq, the problem is that you are treating this as ascii:
```
         raster_filepath = os.path.join(
                temporary_folder,
                layer.title + '.' + extention)
```

but in your case `layer.title` is unicode. Just set the encoding before trying to open the file.

**Comment by cchristelis** [comment]
LGTM

**Pull request merged**
